HubSpot/httpQL

README.rst
pom.xml
src/main/java/com/hubspot/httpql/DefaultMetaUtils.java
src/main/java/com/hubspot/httpql/FieldFactory.java
src/main/java/com/hubspot/httpql/MetaQuerySpec.java
src/main/java/com/hubspot/httpql/ParsedQuery.java
src/main/java/com/hubspot/httpql/ann/OrderBy.java
src/main/java/com/hubspot/httpql/doc/ApiDefinition.java
src/main/java/com/hubspot/httpql/filter/InsensitiveContains.java
src/main/java/com/hubspot/httpql/filter/NotLike.java
src/main/java/com/hubspot/httpql/filter/Range.java
src/main/java/com/hubspot/httpql/impl/DefaultFieldFactory.java
src/main/java/com/hubspot/httpql/impl/FieldFilter.java
src/main/java/com/hubspot/httpql/impl/ParsedUriParams.java
src/main/java/com/hubspot/httpql/impl/PrefixingAliasFieldFactory.java
src/main/java/com/hubspot/httpql/impl/QueryParser.java
src/main/java/com/hubspot/httpql/impl/SelectBuilder.java
src/main/java/com/hubspot/httpql/impl/TableQualifiedFieldFactory.java
src/main/java/com/hubspot/httpql/impl/UriParamParser.java
src/main/java/com/hubspot/httpql/internal/BoundFilterEntry.java
src/main/java/com/hubspot/httpql/jackson/BeanPropertyIntrospector.java
src/main/resources/META-INF/services/com.hubspot.httpql.Filter
src/test/java/com/hubspot/httpql/ParsedQueryTest.java
src/test/java/com/hubspot/httpql/SelectBuilderTest.java
src/test/java/com/hubspot/httpql/impl/QueryParserTest.java
src/test/java/com/hubspot/httpql/impl/UriParamParserTest.java
src/test/java/com/hubspot/httpql/model/EntityWithJoin.java

Updates 
- Updates to `QueryParse` and `SelectBuilder` to handle `@FilterJoin` annotation better
- Remove deprecated `getGenericType` usage in BeanPropertyIntrospector
- Added `NotLike` filter
- Add `isGenerated` flag to `@OrderBy` annotation
- Allow use of custom `QueryParser` and `MetaQuerySpec` implementations
- Add `FieldFilter` and `ParsedUriParams` for higher-level query abstraction without field mapping
- Prevent comma lists on single-value filters
- Add `UriParamParser` for non `QuerySpec` parsing 
- Support `ignoredParams` in `UriParamParser`
- Updates for Jackson changes

HubSpot updates

---

docs/javadoc/com/hubspot/httpql/impl/QueryParser-Builder.rst
docs/javadoc/com/hubspot/httpql/impl/QueryParser.rst
src/main/java/com/hubspot/httpql/impl/QueryParser.java
src/main/java/com/hubspot/httpql/impl/UriParamParser.java
src/test/java/com/hubspot/httpql/impl/UriParamParserTest.java

As discussed on an internal issue, this is part of removing JAX/ Jersey dependencies from `httpQL`.
This PR will be followed by a rebuild of dependent projects (to avoid binary runtime failures) as well as eventual removal of the deprecated methods.
@nbelisle11 @jhaber

Remove uses of MultivaluedMap

---

docs/javadoc/com/hubspot/httpql/impl/QueryParser-Builder.rst
docs/javadoc/com/hubspot/httpql/impl/QueryParser.rst
pom.xml
src/main/java/com/hubspot/httpql/impl/QueryParser.java
src/main/java/com/hubspot/httpql/jersey/BindQueryInjectableProvider.java

This is a follow-up to https://github.com/HubSpot/httpQL/pull/5. See the internal issue for searches that show these are unused.
@nbelisle @boulter 
/cc @jhaber

Remove deprecated methods that operate on UriInfo

---

httpql-jersey1/pom.xml
httpql-jersey1/src/main/java/com/hubspot/httpql/jersey1/BindQuery.java
httpql-jersey1/src/main/java/com/hubspot/httpql/jersey1/BindQueryInjectableProvider.java
pom.xml

This adds the `httpql-jersey1` module for people to get `BindQuery` and `BindQueryInjectableProvider`. 
After merging this, I will migrate our internal uses of these two classes and then remove the deprecated methods.
Any thoughts on naming?
@jhaber @boulter @nbelisle11

Add httpql-jersey1

---

httpql/src/main/java/com/hubspot/httpql/impl/FieldFilter.java

Added toQueryParam method to FieldFilter. I want to use this as a cache key and I could not use toString() method because of the way its formatted.

Added toQueryParam method to FieldFilter

---

httpql/src/main/java/com/hubspot/httpql/filter/IsDistinctFrom.java
httpql/src/main/java/com/hubspot/httpql/filter/IsNotDistinctFrom.java
httpql/src/main/resources/META-INF/services/com.hubspot.httpql.Filter
httpql/src/test/java/com/hubspot/httpql/ParsedQueryTest.java

Currently when we use `not in` or `in` we won't get fields with `NULL` values. This PR adds `isDistinctFrom` to enable queries that return columns with `NULL` values.
See: https://www.jooq.org/javadoc/3.8.x/org/jooq/Field.html#isDistinctFrom-T-

Add isDistinctFrom

---

httpql/src/main/java/com/hubspot/httpql/internal/BoundFilterEntry.java
httpql/src/main/java/com/hubspot/httpql/internal/MultiValuedBoundFilterEntry.java
httpql/src/main/java/com/hubspot/httpql/internal/OverridableBoundFilterEntry.java
httpql/src/test/java/com/hubspot/httpql/SelectBuilderTest.java

The way httpQL is currently setup, it takes the filters and generates BoundFilterEntries from them. This binds all the filters for a query to a single model instance. Meaning that you can't hold more than one value per field. 
This breaks in 2 cases:
- Multi value filters (in, not in, range, etc)
- Combining multiple filters on the same field (e.g. in the case of an OR)
Multi value filters are covered via the [MultiValuedBoundFilterEntry](https://github.com/HubSpot/httpQL/blob/master/httpql/src/main/java/com/hubspot/httpql/internal/MultiValuedBoundFilterEntry.java). This generalizes that approach a bit to a new OverridableBoundFilterEntry.
This is another step to full `OR` support.

Add new OverridableBoundFilterEntry

---

httpql/src/main/java/com/hubspot/httpql/impl/UriParamParser.java
httpql/src/test/java/com/hubspot/httpql/impl/UriParamParserTest.java

In some cases, we will need to allow field names with double underscores in it while filtering. So PR updates the newer version of the method `parseUriParams` which allows double underscores in the field names without breaking existing usages.
One case where this new logic will have issue is when we use implicit `eq` filter with a double underscore field such as `foo__bar=value` and in this case we might need to use the explicit `eq` (`foo__bar__eq=value`) to make this work, otherwise it will consider `bar` as filter and throw invalid filter exception.

Allow double underscore in the field name for filtering

---

httpql/src/main/java/com/hubspot/httpql/impl/QueryParser.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserTest.java

Enables deserialization of `Null` and `NotNull` query parameters, when used for non-string properties.

Support existing behavior for empty-valued query params

---

httpql/src/main/java/com/hubspot/httpql/impl/QueryParser.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserTest.java

Ignore query parameter value for `Null` and `NotNull` filters. 
Supports backwards compatibility for " " to be used as query parameter values for `__is_null` and `__not_null`.

Handle filters that do not require a value

---

httpql/src/test/java/com/hubspot/httpql/SelectBuilderTest.java
pom.xml

Bumping jooq to 3.15.2. It seems like the only behaviour that changed (and were caught by unit tests) is how fields are ordered in the where clauses. 
Starting from jooq-3.15, [jooq only works with Java 11](https://stackoverflow.com/questions/71561604/jooq-throws-class-file-for-java-util-concurrent-flow-not-found-for-where-conditi) so we should probably bump 1.0.0-SNAPSHOT and make a proper release as this could break users of this library.

Bump jooq to 3.15.2

---

pom.xml

Since we bumped the version of jooq in #23, it looks like we're experiencing an unexpected breakage in `duplicate-finder-maven-plugin`. Since that's running a pretty old version by default in basepom, it doesn't perform some checks we'd expect/require (including skipping `module-info` entries). This PR tries bumping the version of that plugin to fix our build
cc @csokol @jhaber

Bump duplicate-finder-maven-plugin to 1.3.0

---

httpql/src/main/java/com/hubspot/httpql/ConditionProvider.java

I'm not 100% sure about what's the point of this method (besides bypassing generics checks). It creates a Param and sets its value right away, so I believe we can simply replace with DSL.value which seems equivalent.
This solves the deprecation warning that pollutes all httpql users' logs.

Avoid using deprecated method

---

httpql/src/main/java/com/hubspot/httpql/ConditionProvider.java

Reverts HubSpot/httpQL#25
The PR broke the build as the lib uses ConditionProvider to create named parameters and there was a small change on how value types are converted (looks like integer/long values are sometimes converted to strings). I'll address the deprecation issue in follow up PR.

Revert "Avoid using deprecated method"

---

httpql/src/main/java/com/hubspot/httpql/ConditionProvider.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserComplexJoinDescriptorTest.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserJoinTest.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserSimpleJoinDescriptorTest.java

Reverts HubSpot/httpQL#27
Reverting this as it caused some build issues internally. Might have to come back to it and maybe release a new version of the library with this change.

Revert "Remove deprecated method usage"

---

httpql/src/main/java/com/hubspot/httpql/DefaultMetaUtils.java
pom.xml

This condition is required to migrate downstream dependencies to `PropertyNamingStrategies` constants and strategy implementations. 
The `PropertyNamingStrategies` class was introduced in 2.12, so the changes also include a version update for the repo - without making changes to basepom.
A search shows no repos in the org's github that use httpQL, and my understanding is that other downstream repos in `git.hubteam` inherit from parent-pom, which is on this updated version.

Upgrade jackson version + add condition on PropertyNamingStrategies.SnakeCaseStrategy

---

httpql/src/main/java/com/hubspot/httpql/Filter.java
httpql/src/main/java/com/hubspot/httpql/Filters.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/ContainsImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/EqualImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/FilterImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/GreaterThanImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/GreaterThanOrEqualImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/InImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/InsensitiveContainsImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/IsDistinctFromImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/IsNotDistinctFromImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/LessThanImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/LessThanOrEqualImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/NotEqualImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/NotInImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/NotLikeImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/NotNullImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/NullImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/RangeImpl.java
httpql/src/main/java/com/hubspot/httpql/impl/filter/StartsWithImpl.java

We can save ourselves some migration work later if we can map the legacy filters to the new FilterImpls directly without having to instantiate one and look it up by name.
Now we can look up FilterImpls by either the old or new classes.

map legacy and new filters

---

httpql-core/pom.xml
httpql-core/src/main/java/com/hubspot/httpql/core/Ordering.java
httpql-core/src/main/java/com/hubspot/httpql/core/OrderingIF.java
httpql-core/src/main/java/com/hubspot/httpql/core/SortOrder.java
httpql-core/src/test/java/com/hubspot/httpql/core/OrderingTest.java
httpql/src/main/java/com/hubspot/httpql/ParsedQuery.java
httpql/src/main/java/com/hubspot/httpql/impl/QueryParser.java
httpql/src/main/java/com/hubspot/httpql/impl/SelectBuilder.java
httpql/src/test/java/com/hubspot/httpql/ParsedQueryTest.java

This adds an interface for ordering that allows either the Ordering implementation in the current module or the new one in the core module to be used. This should make it easier for migrations as the methods can accept either object.

add OrderingIF

---

httpql-core/pom.xml
httpql-core/src/main/java/com/hubspot/httpql/core/Ordering.java
httpql-core/src/main/java/com/hubspot/httpql/core/OrderingIF.java
httpql-core/src/main/java/com/hubspot/httpql/core/SortOrder.java
httpql-core/src/test/java/com/hubspot/httpql/core/OrderingTest.java
httpql/src/main/java/com/hubspot/httpql/ParsedQuery.java
httpql/src/main/java/com/hubspot/httpql/impl/Ordering.java
httpql/src/main/java/com/hubspot/httpql/impl/QueryParser.java
httpql/src/main/java/com/hubspot/httpql/impl/SelectBuilder.java
httpql/src/test/java/com/hubspot/httpql/ParsedQueryTest.java
httpql/src/test/java/com/hubspot/httpql/impl/OrderingTest.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserTest.java

There is some code that relies on the legacy `Ordering` concrete type. We need to migrate those before we can return OrderingIF from these classes.

Fix orderingif

---

httpql-core/src/main/java/com/hubspot/httpql/core/SortOrder.java
httpql/src/main/java/com/hubspot/httpql/ParsedQuery.java
httpql/src/main/java/com/hubspot/httpql/impl/QueryParser.java

This uses the new OrderingsIF in Parsed Query, removing the jooq dependency on Orderings.

Use new Orderings in ParsedQuery

---

httpql/src/main/java/com/hubspot/httpql/ParsedQuery.java

All references have been removed to this method, so it can be safely removed.

remove addOrdering method that uses jooq

---

httpql/src/main/java/com/hubspot/httpql/impl/QueryParser.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserTest.java

This looks for the new and old `QueryConstraints` annotations, so either can be used.

use new queryconstraings

---

httpql/src/main/java/com/hubspot/httpql/DefaultMetaUtils.java
httpql/src/main/java/com/hubspot/httpql/core/ann/FilterJoin.java
httpql/src/main/java/com/hubspot/httpql/core/ann/FilterJoinByDescriptor.java
httpql/src/main/java/com/hubspot/httpql/impl/DefaultMetaQuerySpec.java
httpql/src/main/java/com/hubspot/httpql/impl/FilterJoinInfo.java
httpql/src/main/java/com/hubspot/httpql/internal/BoundFilterEntry.java
httpql/src/test/java/com/hubspot/httpql/model/EntityWithSimpleJoin.java
httpql/src/test/java/com/hubspot/httpql/model/EntityWithSimpleJoinDescriptor.java

This is the last of the new annotations that need to be implemented. The old FilterJoin annotations are still supported.

implement new join descriptors

---

httpql/src/main/java/com/hubspot/httpql/DefaultMetaUtils.java
httpql/src/test/java/com/hubspot/httpql/DefaultMetaUtilsTest.java

This PR removes compile time dependency on Jackson's `LowerCaseWithUnderscoresStrategy` while maintaining backwards compatibility. Jackson removed `LowerCaseWithUnderscoresStrategy` which was already marked for deprecation in later versions of Jackson.

forward compatibility with jackson having removed LowerCaseWithUnderscoresStrategy

---

httpql/src/main/java/com/hubspot/httpql/ConditionProvider.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserComplexJoinDescriptorTest.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserJoinTest.java
httpql/src/test/java/com/hubspot/httpql/impl/QueryParserSimpleJoinDescriptorTest.java

Attempts resolution similar to the one in https://github.com/HubSpot/httpQL/pull/27 but attempts to not run into the same types of failures seen previously. Digging into JOOQ's source, it looks like [DSL::param](https://github.com/jOOQ/jOOQ/blob/2697190c02b60a0cbbb4682e2dae1261a779f62e/jOOQ/src/main/java/org/jooq/impl/DSL.java#L34261) returns a [Val](https://github.com/jOOQ/jOOQ/blob/2697190c02b60a0cbbb4682e2dae1261a779f62e/jOOQ/src/main/java/org/jooq/impl/Val.java#L102) object, which inherits the implementation of method [setConverted0](https://github.com/jOOQ/jOOQ/blob/2697190c02b60a0cbbb4682e2dae1261a779f62e/jOOQ/src/main/java/org/jooq/impl/AbstractParam.java#L166) (which is called via the inherited method [setConverted](https://github.com/jOOQ/jOOQ/blob/2697190c02b60a0cbbb4682e2dae1261 …

Remove setConverted method usage

---

pom.xml

There is a jooq class init cycle in versions less than 3.17.10 that causes our application to occasionally deadlock upon receiving two requests on startup that initialize jooq classes in different orders. See: https://github.com/jOOQ/jOOQ/issues/14769. We have confirmed the same kind of behavior in our application's thread dumps.

Update jooq to prevent class init deadlocks
